### ISSUE TITLE
Prisma cannot find .env defined variable

### ISSUE THREAD

**Issue by wwmike** [delay/sveltekit-auth#1]
Hello!

First, thank you for sharing your starter. I started to explore it, and the following strange issue popped up:
```
PrismaClientInitializationError: 
Invalid `prisma.authKey.findUnique()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:5
   | 
 4 |     provider = "postgresql"
 5 |     url      = env("DATABASE_URL")
```

Even after I change this line in prisma/prisma.schema to url = "postgre...", it still compains about the original file content. ( I verified with vi, the file is changed ). Is there some cache where the file is loaded and never changed again? I ran it with npm run dev, tried stopping and running again, but nothing happened.

Thank you,
Mihaly

**Comment by delay** [comment]
Did you setup your .env file?  You need to change that sample.env to .env and change the name to .env and put your variables in there.  https://github.com/delay/sveltekit-auth/blob/master/sample.env. Also there is a sync command that needs to be run when changing certain variables.  It should run when restarting your dev server.  Also when changing the .env variables you will need to restart your dev server.

**Comment by delay** [comment]
`npx prisma generate` also may need to be run for changes to prisma.

**Comment by wwmike** [comment]
> `npx prisma generate` also may need to be run for changes to prisma.

Thank you! This was needed to make the change visible for prisma in the schema. Based on its script output, it looks like this is handling the .env importing as well:

```
 misi ~/projects/starter-test $ npx prisma generate  
  Environment variables loaded from .env  
  Prisma schema loaded from prisma/schema.prisma

```
After running it, the error is gone.
