### ISSUE TITLE
Code theft

### ISSUE THREAD

**Issue by leafstrat** [delay/sveltekit-auth#4]
Thought I would bring this to your attention;

https://old.reddit.com/r/SvelteKit/comments/1az2esq/sveltekit_template_drizzle_lucia_shadcnsveltekit/
https://github.com/n00ki/kickoff-sveltekit

I first discovered the repo from the reddit thread, and after looking through the libraries it has from that thread I immediately was reminded of your work here. 

I then checked the repo itself and was surprised to see that it was so polished (custom graphic, custom README) with a significant amount of stars.  

My friend did a `diff` on the code from your repo here and their repo, and he found that there was virtually zero differences besides some config file changes. I'm not sure if you can do anything about it, or if you even care, but I wanted to bring it to your attention anyway.

**Comment by delay** [comment]
Thanks for the info. I released my code under MIT license, so people can do with it what they want including re-releasing it.  It would be nice if he gave a mention that he forked it from here, but it isn't required.  I am actually getting ready to release a new auth starter, which has magic link and google Oauth as there were so many changes with lucia, drizzle, superforms, etc.  My goal with releasing these is just to help as many people as possible. I have gotten so much help with my own code from others who have released projects and done tutorials, hopefully people find these starter projects helpful.

**Comment by Antoine-lb** [comment]
I'm the author of the reddit post, sorry about that.
I found the other one first and I was so exited that I posted it on reddit without checking first. I update the reddit post with your repo 🙏

**Comment by delay** [comment]
No problem, thanks so much for updating the post!
