### ISSUE TITLE
No issue just a question

### ISSUE THREAD

**Issue by digitalit** [delay/sveltekit-auth#7]
Hi,

Fist i'd like to thank you for this great repo.

I'm trying to figure out how to get this working on Vercel. I'm new to Vercel and are now using Cleavr.io but i would like to host my Sveltekit sites on Vercel.

This whole serverles thing is a bit confusing for me. I'm used to have a server with Node and Postgres that are identival to my local dev server with only some differences like credentials and what not.

To get the site running on Vercel was quite straight forward but in totally stuck on how to get the postgres part working.

Also i don't really get how to use my local postgres in dev and Vercel postgres on Vercel. I have followed all steps and done the connection with Vercel CLI and i got my local env file but i seemes that now my local site is trying to connect with Vercel and says there are no tables.

Do i need to run migrate on Vercel and if so how?

Thank again and have a nice day.

/Peter (Sweden)

**Comment by delay** [comment]
Sorry I don't use Postgres on Vercel. However wherever you host Postgres you should be able to just put in your connection string in your vercel environmental variables to reference it. Then in your build settings you can run the generate and migrate commands for drizzle as part of the build process. This should update when you make changes to the db. You can also run those commands locally as long as you have the right connection string.

**Comment by digitalit** [comment]
Thank you for a quick answer,

So where do you run Postgres, any tip?

I just want to get your code running on Vercel.

**Comment by delay** [comment]
There are several options. You can run a separate vps. Fly.io offers a free small Postgres instance. There is also neon.tech and xata.io, I think has a Postgres service now too which works with drizzle.

**Comment by digitalit** [comment]
Thank you,

Just one more question, is there a reason why you don't use Vercel Postgres?

Thank you so much again, i won't bother you any more.

**Comment by delay** [comment]
Vercel postgres should also be fine. You can use that one too.
